### Example 2: POST /api/register request without authentication
POST {{host}}/api/register
Content-Type: application/json

{
  "email": "Cook_Programmer@somewhere.com",
  "password": "RecipeInBinary"
}